Users/urls.py
from django.urls import path
from . import views

app_name = 'Users'

urlpatterns = [
    path('', views.index, name='index'),
    path('users/', views.users, name='users'),
    path('<str:_id>/user/', views.user, name='user')
]

example/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('Users.urls'))
]

Users/models.py
from django.db import models

# Create your models here.

Users/views.py
import collections
from re import template
from django.http import HttpResponse, response, Http404
from django.shortcuts import render
from bson.json_util import dumps,loads
from bson.objectid import ObjectId
from pymongo import client_options
import mongoUltis


def index(request):

    db, client = mongoUltis.get_db().users, mongoUltis.get_db()

    collection = db.Users

    users = loads( dumps( list( collection.find({}) ) ) )

    client.close()

    for i in range(0, len(users)):
        users[i]['id'] = str(users[i]['_id'])  

    return render(request, 'Users/index.html', { 'users' : users})


def users(request):
    try:
        db, client = mongoUltis.get_db().users, mongoUltis.get_db()

        collection = db.Users

        users = loads( dumps( list( collection.find({}) ) ) )

        client.close()

        for i in range(0 , len(users)):
        
            users[i]['id'] = str(users[i]['_id'])
            
            date_info = users[i]['date'].split('-')

            users[i]['date'] = { 'dia': date_info[2], 'mes': date_info[1], 'ano': date_info[0]}
    
    except:
        raise Http404("Can't load db info")

    return render(request, 'Users/users.html', { 'users' : users })

def user(request, _id):
    try:
        db, client = mongoUltis.get_db().users, mongoUltis.get_db()

        collection = db.Users
        user = loads( dumps( collection.find_one( {'_id' : ObjectId(_id) , } ) ) )

        user['id'] = str(user['_id'])

        client.close()

        date_info = user['date'].split('-')

        user['date'] = { 'dia': date_info[2], 'mes': date_info[1], 'ano': date_info[0]}

    except:
        raise Http404("User does not Exist")

    return render(request, 'Users/user.html', { 'user' : user})

Users/templates/Users/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    {% load static %}

    <link rel="stylesheet" type="text/css" href="{% static 'Users/index.css' %}">
    
    <title>HomePage</title>
</head>
<body>
    
    <div class="container">
        <h1 class="title">Users</h1>
    
        {% for user in users %}
        
            <a href="{% url  'Users:user' user.id %}"> <div class="element"> {{ user.username }} </div> </a>

        {% endfor %}
            <a href="users/"> <div class="all_elements"> All </div> </a>
    </div>

</body>
</html>

Users/templates/Users/user.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}

    <link rel="stylesheet" href="{% static 'Users/user.css' %}">

    <title>User Data</title>
</head>

<body>
    
    <div class="container">
        
        <h1>{{ user.username }} </h1>
            
        <ul>
            <li> {{ user.id }}   </li>
            <li> {{ user.date.dia }} &#47; {{ user.date.mes }} &#47; {{ user.date.ano }} </li>
            <li> {{ user.email }} </li>
        <ul>

    </div>

</body>

</html>

Users/templates/Users/users.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}

    <link rel="stylesheet" href="{% static 'Users/users.css' %}">

    <title>Users Table</title>
</head>
<body>
    <div class="container">

        <div id="box-table">       

                <table id="user-table"> 
                        <tr class="box-table" style="background-color: #8a2be2; color: #fff;">
                            <th>ID</th>

                            <th>UserName</th>
            
                            <th>Email</th>
                            
                            <th>Date</th>
                            
                            <th>Password</th>
                        </tr>
            
                        {% for user in users %}
                        
                            <tr class="box-table">
                                
                                <td> {{ user.id }} </td>
        
                                <td> {{ user.username }} </td>
        
                                <td> {{ user.email }} </td>
                                
                                <td> {{ user.date.dia }} &#47; {{ user.date.mes }} &#47; {{ user.date.ano }} </td>
                                
                                <td> {{ user.password }} </td>
        
                            </tr>
                        
                        {% endfor %}
                </table>
        </div>

    </div>
</body>
</html>

<!-- <table>
    <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Date</th>
    </tr>
    {% for user in users %}
        <tr>
            <td>{{ user.username }}</td>
            <td>{{ user.email }}</td>
            <td>{{ user.date }}</td>
        </tr>
    {% endfor %}
</table> -->